Repository decentralised-dataexchange/bb-consent-api, pull requests merged in 2023-10, with the labels that each got.

#203 Add #201 Ability to configure default organisation and types on initi…
  src/config/config.go
  src/handlerv1/organization_handler.go
  src/main/main.go
  src/main/single_tenant.go
  src/middleware/middleware.go
  src/org/organizations.go
  src/orgtype/orgType.go
  src/user/users.go
Labels: enhancement

#214 Add #204 Align onboard APIs
  src/common/utils.go
  src/handlerv2/getorganizationbyid_handler.go
  src/handlerv2/gettoken_handler.go
  src/handlerv2/loginadminuser_handler.go
  src/handlerv2/loginuser_handler.go
  src/handlerv2/updateorganization_handler.go
  src/handlerv2/updateorganizationcoverimage_handler.go
  src/handlerv2/updateorganizationlogoimage_handler.go
  src/handlerv2/validatephonenumber_handler.go
  src/handlerv2/validateuseremail_handler.go
  src/handlerv2/verifyotp_handler.go
  src/handlerv2/verifyphonenumber_handler.go
  src/httppathsv2/routes.go
  src/otp/otps.go
  src/user/users.go
Labels: enhancement

#220 Fix #219 Fix user object to ensure backward compatibility
  src/user/users.go
Labels: bug

#222 Fix #221 Add middleware to add response header - Content-Type
  src/httppathsv2/routes.go
  src/middleware/middleware.go
Labels: bug

#227 Fix 226: Add missing 'description' field in the get organisation response
  src/handlerv2/getorganizationbyid_handler.go
Labels: bug

#238 Fix #234 Content type for all error messages in the response should b…
  src/httppathsv2/routes.go
Labels: bug

#239 Fix #236 Refresh token endpoint returns 404
  src/httppathsv2/onboard_paths.go
Labels: bug

#242 Fix #237 Validate phone endpoints returns error
  src/handlerv2/validatephonenumber_handler.go
Labels: bug

#243 Fix #241 Support DPIA configuration in v1 data agreement endpoints
  src/handlerv1/organization_handler.go
  src/org/organizations.go
Labels: bug

#252 Add #244 Integrate policy endpoints
  src/common/utils.go
  src/config/constants.go
  src/database/db.go
  src/handlerv2/addglobalpolicyconfigurations_handler.go
  src/handlerv2/getglobalpolicyconfigurations_handler.go
  src/handlerv2/orgdeletepolicy_handler.go
  src/handlerv2/orglistpolicy_handler.go
  src/handlerv2/orglistpolicyrevisions_handler.go
  src/handlerv2/updateglobalpolicyconfigurationbyid_handler.go
  src/handlerv2/updateglobalpolicyconfigurations_handler.go
  src/httppathsv2/config_paths.go
  src/httppathsv2/routes.go
  src/paginate/paginate.go
  src/policy/policy.go
  src/policy/revision.go
Labels: enhancement

#257 Fix #256 Support storage location configiration on v1 data agreement
  src/org/organizations.go
  src/v1/handler/organization_handler.go
Labels: bug

#261 Fix #260 Pass empty array instead of null value if response is empty …
  src/v1/handler/organization_handler.go
Labels: bug

#264 Fix #240 Change the response for update organisation endpoint
  src/v2/handler/updateorganization_handler.go
Labels: bug

#263 Add #245 Integrate data agreement endpoints
  src/common/db.go
  src/config/constants.go
  src/dataagreement/dataagreements.go
  src/database/db.go
  src/revision/db.go
  src/revision/revisions.go
  src/v2/handler/adddataagreement_handler.go
  src/v2/handler/adddataattribute_handler.go
  src/v2/handler/dataagreement/config_create_dataagreement.go
  src/v2/handler/dataagreement/config_delete_dataagreement.go
  src/v2/handler/dataagreement/config_list_dataagreement_revisions.go
  src/v2/handler/dataagreement/config_list_dataagreements.go
  src/v2/handler/dataagreement/config_read_dataagreement.go
  src/v2/handler/dataagreement/config_update_dataagreement.go
  src/v2/handler/deletedataagreement_handler.go
  src/v2/handler/getdataagreementbyid_handler.go
  src/v2/handler/listdataagreementrevisions_handler.go
  src/v2/handler/listdataagreements_handler.go
  src/v2/handler/readdataagreementrevision_handler.go
  src/v2/handler/updatedataagreement_handler.go
  src/v2/http_path/config_paths.go
  src/v2/http_path/routes.go
Labels: enhancement

#267 Fix #266 Update validation for data agreement endpoints
  src/dataagreement/dataagreements.go
  src/revision/revisions.go
  src/v2/handler/dataagreement/config_create_dataagreement.go
Labels: bug

#276 Add #274 Process webhooks in goroutine
  src/main/main.go
  src/v2/webhook/db.go
  src/v2/webhook/webhook.go
  src/v2/webhook_dispatcher/db.go
  src/v2/webhook_dispatcher/webhookdispatcher.go
Labels: enhancement

#277 Add #271 Keycloak: Migrate from homebrewed API calls to gocloak
  go.mod
  go.sum
  src/v2/handler/individual/config_create_individual.go
  src/v2/handler/individual/config_delete_user.go
  src/v2/handler/individual/config_update_individual.go
Labels: enhancement

#282 Add #248 Integrate IDP endpoints
  go.mod
  go.sum
  src/config/constants.go
  src/database/db.go
  src/main/main.go
  src/v2/error_handler/error_handler.go
  src/v2/handler/addidentityprovider_handler.go
  src/v2/handler/deleteidentityprovider_handler.go
  src/v2/handler/getidentityprovider_handler.go
  src/v2/handler/idp/config_create_idp.go
  src/v2/handler/idp/config_delete_idp.go
  src/v2/handler/idp/config_get_idp.go
  src/v2/handler/idp/config_update_idp.go
  src/v2/handler/individual/config_create_individual.go
  src/v2/handler/individual/config_delete_user.go
  src/v2/handler/individual/config_update_individual.go
  src/v2/handler/onboard/getorganizationbyid_handler.go
  src/v2/handler/onboard/getorganizationcoverimage_handler.go
  src/v2/handler/onboard/getorganizationlogoimage_handler.go
  src/v2/handler/onboard/gettoken_handler.go
  src/v2/handler/onboard/loginadminuser_handler.go
  src/v2/handler/onboard/loginuser_handler.go
  src/v2/handler/onboard/onboard_exchange_authorization_code.go
  src/v2/handler/onboard/updateorganization_handler.go
  src/v2/handler/onboard/updateorganizationcoverimage_handler.go
  src/v2/handler/onboard/updateorganizationlogoimage_handler.go
  src/v2/handler/onboard/validatephonenumber_handler.go
  src/v2/handler/onboard/validateuseremail_handler.go
  src/v2/handler/onboard/verifyotp_handler.go
  src/v2/handler/onboard/verifyphonenumber_handler.go
  src/v2/handler/updateidentityprovider_handler.go
  src/v2/http_path/onboard_paths.go
  src/v2/http_path/routes.go
  src/v2/iam/iam.go
  src/v2/idp/idp.go
  src/v2/individual/individuals.go
  src/v2/middleware/application_mode.go
  src/v2/middleware/authenticate.go
  src/v2/middleware/authorise.go
  src/v2/middleware/content_type.go
  src/v2/middleware/logger.go
  src/v2/middleware/logger_no_auth.go
  src/v2/middleware/middleware.go
  src/v2/sms/twilio.go
Labels: enhancement

#290 Fix #279 lifecycle field in the data agreement should be populated based on the value of active field
  src/v2/handler/dataagreement/config_create_dataagreement.go
  src/v2/handler/dataagreement/config_update_dataagreement.go
Labels: bug

#304 Fix #293 In single tenant configuration, admin should be created only…
  src/main/single_tenant.go
Labels: bug

#308 Add #296 Get/Update organisation admin profile
  src/v2/handler/onboard/onboard_read_organisation_admin.go
  src/v2/handler/onboard/onboard_update_organisation_admin.go
  src/v2/http_path/onboard_paths.go
  src/v2/http_path/routes.go
  src/v2/iam/iam.go
Labels: enhancement

#309 Add #297 Reset password
  src/v2/handler/onboard/onboard_reset_password.go
  src/v2/http_path/onboard_paths.go
  src/v2/http_path/routes.go
  src/v2/iam/iam.go
Labels: enhancement

#310 Add #303 Forgot password for consent bb individuals and not for indiv…
  src/v2/handler/onboard/onboard_forgot_password.go
  src/v2/http_path/onboard_paths.go
  src/v2/http_path/routes.go
  src/v2/iam/iam.go
Labels: enhancement

#314 Add #300 Add filter by active for data agreements
  src/v2/handler/dataagreement/config_list_dataagreements.go
Labels: enhancement

#315 Add #302 Add endpoint for admin logs
  src/v2/actionlog/actionlog.go
  src/v2/actionlog/actionlog_utils.go
  src/v2/handler/audit/audit_admin_logs.go
  src/v2/handler/onboard/loginadminuser_handler.go
  src/v2/handler/webhook/config_redeliver_webhook_payload_by_deliveryid.go
  src/v2/http_path/audit_paths.go
  src/v2/http_path/routes.go
  src/v2/webhook/webhook.go
Labels: enhancement

#313 Add #312 Read or Update organisation admin avatar image
  src/v2/handler/onboard/onboard_read_org_admin_avathar.go
  src/v2/handler/onboard/onboard_update_org_admin_avathar.go
  src/v2/http_path/onboard_paths.go
  src/v2/http_path/routes.go
Labels: enhancement

#320 Fix #311 Add third party sharing to policy
  src/policy/policy.go
  src/v2/handler/policy/config_create_policy.go
  src/v2/handler/policy/config_update_policy.go
Labels: bug

#321 Add #259 In single tenant mode, only one policy is allowed
  src/policy/policy.go
  src/v2/handler/policy/config_create_policy.go
Labels: enhancement

#322 Add #291 Add last visited to organisation admin read or update response
  src/v2/handler/onboard/onboard_read_organisation_admin.go
  src/v2/handler/onboard/onboard_update_org_admin_avathar.go
  src/v2/handler/onboard/onboard_update_organisation_admin.go
Labels: enhancement

#330 Fix #328 In create policy, the response should contain dataRetentionP…
  src/policy/policy.go
Labels: bug

#327 Add #325 Integrate data agreement record endpoints
  src/common/utils.go
  src/config/constants.go
  src/database/db.go
  src/v2/dataagreement_record/dataagreement_record.go
  src/v2/dataagreement_record/db.go
  src/v2/dataagreement_record_history/dataagreement_record_history.go
  src/v2/dataagreement_record_history/db.go
  src/v2/handler/service/service_create_blank_signature_object.go
  src/v2/handler/service/service_create_dataagreement_record.go
  src/v2/handler/service/service_create_draft_consent_record.go
  src/v2/handler/service/service_create_paired_dataagreement_record.go.go
  src/v2/handler/service/service_delete_individual_dataagreement_records.go
  src/v2/handler/service/service_fetch_data_agreement_records.go
  src/v2/handler/service/service_fetch_dataagreement_records_history.go
  src/v2/handler/service/service_fetch_individual_dataagreement_records.go
  src/v2/handler/service/service_fetch_records_for_data_agreement.go
  src/v2/handler/service/service_read_data_agreement_record.go
  src/v2/handler/service/service_update_dataagreement_record.go
  src/v2/handler/service/service_update_signature_object.go
  src/v2/handler/service/service_verification_fetch_dataagreement_record.go
  src/v2/handler/service/service_verification_fetch_dataagreement_records.go
  src/v2/handler/service/servicecreateindividualconsentrecord_handler.go
  src/v2/handler/service/servicelistindividualrecordlist_handler.go
  src/v2/handler/service/servicereadindividualrecordread_handler.go
  src/v2/handler/service/serviceupdateindividualconsentrecord_handler.go
  src/v2/handler/service/serviceverificationagreementconsentrecordread_handler.go
  src/v2/handler/service/serviceverificationagreementlist_handler.go
  src/v2/handler/service/serviceverificationconsentrecordlist_handler.go
  src/v2/http_path/routes.go
  src/v2/http_path/service_paths.go
  src/v2/middleware/authenticate.go
  src/v2/revision/db.go
  src/v2/revision/revisions.go
  src/v2/signature/db.go
  src/v2/signature/signature.go
  src/v2/token/token.go
Labels: enhancement

#344 Add #207 align audit apis
  src/config/constants.go
  src/v2/dataagreement_record/dataagreement_record.go
  src/v2/dataagreement_record/db.go
  src/v2/handler/audit/audit_list_dataagreement_records.go
  src/v2/handler/audit/audit_list_dataagreements.go
  src/v2/handler/audit/audit_read_dataagreement.go
  src/v2/handler/audit/audit_read_dataagreement_record.go
  src/v2/handler/audit/auditagreementlist_handler.go
  src/v2/handler/audit/auditconsentrecordlist_handler.go
  src/v2/handler/audit/auditconsentrecordread_handler.go
  src/v2/handler/audit/auditreadrecord_handler.go
  src/v2/http_path/audit_paths.go
  src/v2/http_path/routes.go
Labels: enhancement

#348 Add #346 Audit: Add dataAgreement and timestamp fields in list data a…
  src/v2/dataagreement_record/dataagreement_record.go
  src/v2/dataagreement_record/db.go
  src/v2/handler/audit/audit_list_dataagreement_records.go
Labels: enhancement

#351 Fix #349 List all organisation admin logs requires Timestamp in the r…
  src/v2/actionlog/actionlog.go
Labels: bug

#352 Add #336 Add GET /service/organisation endpoint
  src/v2/handler/service/service_read_organisation.go
  src/v2/http_path/routes.go
  src/v2/http_path/service_paths.go
Labels: enhancement

#355 Add #354 Add List Api key Endpoint
  src/v2/handler/apikey/config_list_apikeys.go
  src/v2/http_path/config_paths.go
  src/v2/http_path/routes.go
Labels: enhancement

#356 Add #183 Event lists in webhook should be configured
  src/config/config.go
  src/kafkaUtils/kafka.go
  src/main/main.go
  src/v1/handler/webhooks_handler.go
  src/v2/handler/webhook/config_list_webhook_event_types.go
  src/v2/handler/webhook/config_redeliver_webhook_payload_by_deliveryid.go
  src/v2/webhook/webhook.go
  src/webhookdispatcher/webhookdispatcher.go
  src/webhooks/webhooks.go
Labels: enhancement

#359 Fix #332 On updating organisation name, it empties the sector
  src/v2/handler/onboard/updateorganization_handler.go
Labels: bug

#363 Add #361 Add service endpoints read organisation logo image and cover…
  src/v2/handler/service/service_read_organisation_logo_image.go
  src/v2/handler/service/service_read_organistaion_cover_image.go
  src/v2/http_path/routes.go
  src/v2/http_path/service_paths.go
Labels: enhancement

#358 Add #166 Ability to configure privacy dashboard
  src/config/config.go
  src/main/main.go
  src/v2/handler/privacy_dashboard/config_read_privacy_dashboard.go
  src/v2/http_path/config_paths.go
  src/v2/http_path/routes.go
  src/v2/privacy_dashboard/privacy_dashboard.go
Labels: enhancement

#365 Add #364 Data agreement update should not increment version if it is …
  src/v2/handler/dataagreement/config_update_dataagreement.go
Labels: enhancement

#371 Fix #369 Webhooks recent delivery api giving 404 error
  src/v2/http_path/config_paths.go
Labels: bug

#373 Add #372 Add onboard read status endpoint
  src/v2/handler/onboard/onboard_read_status.go
  src/v2/http_path/onboard_paths.go
  src/v2/http_path/routes.go
  src/v2/version/version.go
Labels: enhancement

#378 Add #376 Trigger webhook when consent is allowed and disallowed if we…
  src/v2/handler/service/service_create_dataagreement_record.go
  src/v2/handler/service/service_create_paired_dataagreement_record.go.go
  src/v2/handler/service/service_update_dataagreement_record.go
  src/v2/webhook/webhook.go
Labels: enhancement

#386 Fix #384 logo image and cover image is not updating in response
  src/org/organizations.go
  src/v2/handler/onboard/onboard_read_organisation.go
  src/v2/handler/onboard/updateorganization_handler.go
  src/v2/handler/onboard/updateorganizationcoverimage_handler.go
  src/v2/handler/onboard/updateorganizationlogoimage_handler.go
  src/v2/handler/service/service_read_organisation.go
Labels: bug

#388 Add #387 Update audit list data agreement records to use id field as …
  src/config/constants.go
  src/database/db.go
  src/v2/dataagreement_record/dataagreement_record.go
  src/v2/dataagreement_record/db.go
  src/v2/handler/audit/audit_list_dataagreement_records.go
  src/v2/paginate/paginate.go
Labels: bug

#389 Fix #380 View logs list api sort based on Descending order
  src/v2/handler/audit/audit_admin_logs.go
Labels: bug

#391 Fix #390 Api crashing
  src/v1/handler/organization_handler.go
Labels: bug

#397 Fix #392 Safeguard measure: Create data agreement record for same ind…
  src/v2/dataagreement_record/db.go
  src/v2/handler/service/service_create_dataagreement_record.go
  src/v2/handler/service/service_create_paired_dataagreement_record.go.go
Labels: bug

#398 Fix #394 Delete data agreement records for a data agreement if that d…
  src/v2/dataagreement_record/db.go
  src/v2/handler/dataagreement/config_delete_dataagreement.go
Labels: bug

#399 Fix #396 Refactor fetch all data agreement records to use updated pip…
  src/v2/dataagreement_record/db.go
  src/v2/handler/audit/audit_list_dataagreement_records.go
  src/v2/paginate/paginate.go
Labels: bug

#400 Fix #395 Sort by timestamp in descending order for all listing endpoints
  src/policy/policy.go
  src/v2/dataagreement/dataagreements.go
  src/v2/dataagreement_record/db.go
  src/v2/handler/audit/audit_list_dataagreements.go
  src/v2/handler/dataagreement/config_list_dataagreements.go
  src/v2/handler/policy/config_list_policies.go
  src/v2/handler/service/service_fetch_data_agreement_records.go
  src/v2/handler/service/service_fetch_individual_dataagreement_records.go
  src/v2/handler/service/service_fetch_records_for_data_agreement.go
  src/v2/handler/service/service_list_dataagreements.go
  src/v2/handler/service/service_verification_fetch_dataagreement_records.go
  src/v2/revision/db.go
Labels: bug

#401 Add #347 Draft data agreements shouldn't require any mandatory fields
  go.mod
  go.sum
  src/v2/handler/dataagreement/config_create_dataagreement.go
Labels: enhancement

#409 Fix #407 Do NOT delete consent records when data agreement is deleted
  internal/dataagreement_record/db.go
  internal/handler/v2/config/dataagreement/config_delete_dataagreement.go
  internal/handler/v2/service/service_update_dataagreement_record.go
Labels: bug

#411 Fix #410 Refactor iam
  internal/handler/v2/config/individual/config_create_individual.go
  internal/handler/v2/config/individual/config_delete_user.go
  internal/handler/v2/config/individual/config_update_individual.go
  internal/handler/v2/service/individual/service_create_individual.go
  internal/handler/v2/service/individual/service_update_individual.go
  internal/iam/iam.go
Labels: bug

#413 Add #412 Default application mode should be single-tenant
  internal/cmd/start_api.go
  internal/middleware/application_mode.go
Labels: enhancement

#419 Feature/add instructions to run
  README.md
Labels: documentation, enhancement

#421 Fix #347 Draft data agreements shouldn't require any mandatory fields
  internal/handler/v2/config/dataagreement/config_create_dataagreement.go
  internal/handler/v2/config/dataagreement/config_update_dataagreement.go
Labels: bug

#420 Fix #418 Draft data agreement in read and delete dataagreement endpoi…
  internal/handler/v2/config/dataagreement/config_delete_dataagreement.go
  internal/handler/v2/config/dataagreement/config_read_dataagreement.go
  internal/revision/revisions.go
Labels: bug

#426 Fix #424 Error in Mongo; no documents in the result for update and publish data agreements
  internal/handler/v2/config/dataagreement/config_create_dataagreement.go
  internal/handler/v2/config/dataagreement/config_delete_dataagreement.go
  internal/handler/v2/config/dataagreement/config_read_dataagreement.go
  internal/handler/v2/config/dataagreement/config_update_dataagreement.go
  internal/handler/v2/config/dataattribute/config_update_dataattribute.go
Labels: bug
